#!/bin/bash
#    An automated script to run pyperformane using specified python binaries
#    Copyright (C) 2024 David Valin <dvalin@redhat.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, see <https://www.gnu.org/licenses/>.

PATH="${PATH}:/usr/local/bin"
export PATH
python_pkgs=""
python_exec="python3"
install_pip=0
PYTHON_VERSION=""
PYPERF_VERSION="1.11.0"
copy_dirs=""
benchmarks="all"
test_name="pyperf"
rtc=0

TOOLS_BIN="$HOME/test_tools"
export TOOLS_BIN

base_dir=$(dirname $(realpath $0))
#
# To make sure.
#
exit_out()
{
	if [[ $to_use_pcp -eq 1 ]]; then
		stop_pcp_subset
		stop_pcp
		shutdown_pcp
	fi

	echo $1
	exit $2
}

usage()
{
	echo "$1 Usage:"
	echo "--pyperf_version <version number>: Version of pyperf to run, default is $PYPERF_VERSION."
	echo "--python_exec_path: Python to set via alternatives"
	echo "--python_pkgs: comma seprated list of python packages to install"
	echo "--pyperf_benchmarks: Comma separated list of pyperformance benchmarks to run.  Default is to run all tests."
	source $TOOLS_BIN/general_setup --usage
        exit $E_USAGE
}

verify_benchmark_names()
{
	benchmark_file=$(mktemp pyperf_benchmarks.XXXXX)
	$python_exec -m pyperformance list | head -n -2 | tail -n +2 | sed -e 's/- //g' > $benchmark_file
	invalid_benchmarks=""
	for benchmark in $(echo $benchmarks | tr ',' ' '); do
		grep $benchmark $benchmark_file > /dev/null

		if [[ $? -ne 0 ]]; then
			invalid_benchmarks="$benchmark $invalid_benchmarks"
		fi
	done

	rm -f $benchmark_file

	if [[ -n "$invalid_benchmarks" ]]; then
		exit_out "Error: Could not find the following benchmarks $invalid_benchmarks" $E_GENERAL
	fi
}

setup_pyperformance()
{
	major=$(echo $PYPERF_VERSION | cut -d. -f1)
	minor=$(echo $PYPERF_VERSION | cut -d. -f2)

	$python_exec -m pyperformance venv create
	venv_path=$($python_exec -m pyperformance venv show | sed -e "s/Virtual environment path: //g" -e "s/ (already created)//" )

	if [[ -z "$venv_path" ]]; then
		exit_out "Error: Could not determine pyperformance venv path, exiting" $E_GENERAL
	fi
	if [[ ! -x "$venv_path/bin/python3" ]]; then
		exit_out "Error: Could not find interpreter at $venv_path/bin/python3, exiting" $E_GENERAL
	fi

	# Revert to setuptools v81.0.0 due to `pkg_resources` removal at v82.0.0
	# https://setuptools.pypa.io/en/stable/history.html#deprecations-and-removals
	# Skipping using pkg_tool to ensure that all relevant venv PATHs are honored
	if [[ "$major" -le 1 ]] && [[ "$minor" -le 11 ]]; then
		echo "Detected <=1.11.0, applying setuptools fix"
		"$venv_path/bin/python3" -m pip install --upgrade setuptools==81.0.0 # Execute venv pip instead
	fi
}

attempt_tools_wget()
{
        if [[ ! -d "$TOOLS_BIN" ]]; then
                wget ${tools_git}/archive/refs/heads/main.zip
                if [[ $? -eq 0 ]]; then
                        unzip -q main.zip
                        mv test_tools-wrappers-main ${TOOLS_BIN}
                        rm main.zip
                fi
        fi
}

attempt_tools_curl()
{
        if [[ ! -d "$TOOLS_BIN" ]]; then
                curl -L -O ${tools_git}/archive/refs/heads/main.zip
                if [[ $? -eq 0 ]]; then
                        unzip -q main.zip
                        mv test_tools-wrappers-main ${TOOLS_BIN}
                        rm main.zip
                fi
        fi
}

attempt_tools_git()
{
        if [[ ! -d "$TOOLS_BIN" ]]; then
                git clone $tools_git "$TOOLS_BIN"
                if [ $? -ne 0 ]; then
                        exit_out "Error: pulling git $tools_git failed." 101
                fi
        fi
}

install_tools()
{
	show_usage=0
	#
	# Clone the repo that contains the common code and tools
	#
	tools_git=https://github.com/redhat-performance/test_tools-wrappers

	found=0
	for arg in "$@"; do
		if [ $found -eq 1 ]; then
			tools_git=$arg
			found=0
		fi
		if [[ $arg == "--tools_git" ]]; then
			found=1
		fi
		#
		# We do the usage check here, as we do not want to be calling
		# the common parsers then checking for usage here.  Doing so will
		# result in the script exiting with out giving the test options.
		#
		if [[ $arg == "--usage" ]]; then
			show_usage=1
		fi
	done

	#
	# Check to see if the test tools directory exists.  If it does, we do not need to
	# clone the repo.
	#

	attempt_tools_wget
	attempt_tools_curl
	attempt_tools_git

	if [ $show_usage -eq 1 ]; then
		usage $1
	fi
}

generate_csv_file()
{
	instance=0
	float=0
	ivalue=0
	fvalue=0.0
	test_name=""
	unit=""
	reduce=0
	res_count=0
	value_sum=0
	start_time=$2
	end_time=$3

	$TOOLS_BIN/test_header_info --front_matter --results_file "${1}.csv" --host $to_configuration --sys_type $to_sys_type --tuned $to_tuned_setting --results_version "py${PYTHON_VERSION}_$PYPERF_VERSION" --test_name $test_name_run --field_header "Test,Avg,Unit"


	while IFS= read -r line
	do
		if [[ $test_name == "" ]]; then
			test_name=$line
			continue
		fi
		if [[ $line == *"Try to rerun "* ]]; then
			continue
		fi
		if [ -z "$line" ]; then
			let "reduce=$reduce+1"
			if [[ $reduce -eq 2 ]]; then
				if [[ $test_name != *"WARNING:"* ]]; then
					results=$(echo "${value_sum}/${res_count}" | bc)
					#
					# Timings is in seconds
					#
					sec_results=$(${TOOLS_BIN}/convert_val --time_val --from_unit  ns --to_unit secs --value $results --float --no_unit)
					printf "%s,%.9f,sec,%s,%s\n" $test_name $sec_results $start_time $end_time >> ${1}.csv
					
					if [[ $to_use_pcp -eq 1 ]]; then
						metric_name="pyperf_${test_name}"
						result2pcp "$metric_name" "${sec_results}"
					fi
				fi
				reduce=0
				res_count=0
				value_sum=0
				test_name=""
			fi
			continue
		fi
		if [[ $line == *"--"* ]] || [[ $line == *"calibrate"* ]] || [[ $line == *"warmup"* ]] || [[ $line != *"value"* ]]; then
			continue
		fi
		value=`echo $line | cut -d' ' -f 4`
		unit=`echo $line | cut -d' ' -f 5`
		cnv_val=$($TOOLS_BIN/convert_val --time_val --from_unit  $unit --to_unit ns --value $value --no_unit)
		let "res_count=${res_count}+1"
		value_sum=`echo "${cnv_val}+${value_sum}" | bc`
	done < "${1}.results"

	if [[ $test_name != *"WARNING:"* ]]; then
		results=$(echo "${value_sum}/${res_count}" | bc | cut -d'.' -f1 )
		#
		# Timings is in seconds
		#
		sec_results=$(${TOOLS_BIN}/convert_val --time_val --from_unit  ns --to_unit secs --value $results --float --no_unit)
		printf "%s,%.9f,sec,%s,%s\n" $test_name $sec_results $start_time $end_time >> ${1}.csv

		if [[ $to_use_pcp -eq 1 ]]; then
			metric_name="pyperf_${test_name}"
			result2pcp "$metric_name" "${sec_results}"
		fi
	fi
}

pip3_install()
{
	if [ $to_no_pkg_install -eq 1 ]; then
		return
	fi

	$python_exec -m pip --version
	if [[ $? -ne 0 ]]; then
			if [[ $install_pip -eq 1 ]]; then
			$python_exec -m ensurepip || exit_out "Failed to install pip." $E_GENERAL
		else
			exit_out "Pip is not available, exiting out" $E_GENERAL
		fi
	fi

	$python_exec -m pip install -q $1
	if [[ $? -ne 0 ]]; then
		exit_out "Pip not available for install of $1 failed." $E_GENERAL
	fi
}
#
# Variables set by general setup.
#
# TOOLS_BIN: points to the tool directory
# to_home_root: home directory
# to_configuration: configuration information
# to_times_to_run: number of times to run the test
# to_user: User on the test system running the test
# to_sys_type: for results info, basically aws, azure or local
# to_sysname: name of the system
# to_tuned_setting: tuned setting
#

install_tools $0

test_name_run="pyperf"
arguments="$@"

curdir=`pwd`

if [[ $0 == "./"* ]]; then
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	if [[ $chars == 1 ]]; then
		run_dir=`pwd`
	else
		run_dir=`echo $0 | cut -d'/' -f 1-${chars} | cut -d'.' -f2-`
		run_dir="${curdir}${run_dir}"
	fi
elif [[ $0 != "/"* ]]; then
	dir=`echo $0 | rev | cut -d'/' -f2- | rev`
	run_dir="${curdir}/${dir}"
else
	chars=`echo $0 | awk -v RS='/' 'END{print NR-1}'`
	run_dir=`echo $0 | cut -d'/' -f 1-${chars}`
	if [[ $run_dir != "/"* ]]; then
		run_dir=${curdir}/${run_dir}
	fi
fi

# Gather hardware information
$TOOLS_BIN/gather_data ${curdir}

exec &> >(tee /tmp/pyperf.out)

if [ -d "workloads" ]; then
	#
	# If running from zathras, workloads will be symlinked to
	# to /mnt.  Which is done due to azure having a very small
	# user space.
	#
	start_dir=`pwd`
	cd workloads
	for file in `ls ${start_dir}`; do
		if [[ ! -f $file ]] && [[ ! -d $file ]]; then
			ln -s $start_dir/$file .
		fi
	done
fi

source $TOOLS_BIN/general_setup "$@"

ARGUMENT_LIST=(
	"pyperf_version"
	"python_exec"
	"python_pkgs"
	"pyperf_benchmarks"
)

NO_ARGUMENTS=(
	"usage"
	"install_pip"
)

# read arguments
opts=$(getopt \
	--longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
        --longoptions "$(printf "%s," "${NO_ARGUMENTS[@]}")" \
        --name "$(basename "$0")" \
        --options "h" \
        -- "$@"
)

eval set --$opts

while [[ $# -gt 0 ]]; do
	case "$1" in
		--pyperf_version)
			PYPERF_VERSION=$2
			shift 2
		;;
		--python_exec)
			python_exec=$2
			shift 2
		;;
		--python_pkgs)
			python_pkgs=$2
			shift 2
		;;
		--install_pip)
			install_pip=1
			shift 1
		;;
		--pyperf_benchmarks)
			benchmarks=$2
			shift 2
		;;
		--usage)
			usage $0
		;;
		-h)
			usage $0
		;;
		--)
			break
		;;
		*)
			echo option not found $1
			usage $0
		;;
	esac
done

if ! command -v "$python_exec" > /dev/null; then
	exit_out "Error: $python_exec either doesn't exist or is not executable!" $E_GENERAL
fi

PYTHON_VERSION=$($python_exec --version | awk '{ print $2 }')
if [[ ${python_pkgs} != "" ]]; then
	pkg_list="--packages `echo $python_pkgs | sed "s/,/ /g"`"
fi
if ! command -v $python_exec; then
	exit_out "Error: Designated python executable, $python_exec, not present" $E_GENERAL
fi

if [[  $to_no_pkg_install -eq 0 ]]; then
	python_bin_name=$(basename $python_exec)
	python_dep_file="$base_dir/../python_deps/$python_bin_name.json"
	if [[ ! -f "$python_dep_file" ]]; then
		exit_out "Unsupported python binary $python_bin_name, exiting" $E_GENERAL
	fi

	package_tool --wrapper_config $python_dep_file

	if [[ $? -ne 0 ]]; then
		exit_out "Error installing needed python dependencies" $E_GENERAL
	fi

	package_tool --wrapper_config $base_dir/../pyperf.json $pkg_list --pip_packages "pyperformance==$PYPERF_VERSION"

	if [[ $? -ne 0 ]]; then
		exit_out "Error installing system packages" $E_GENERAL
	fi
fi

cpus=`cat /proc/cpuinfo | grep processor | wc -l`
cous=1
mkdir python_results

pyresults=python_results/pyperf_out_$(date "+%Y.%m.%d-%H.%M.%S")

if [[ $to_use_pcp -eq 1 ]]; then
	source $TOOLS_BIN/pcp/pcp_commands.inc
	setup_pcp
	pcp_cfg=$TOOLS_BIN/pcp/default.cfg
	pcp_dir=/tmp/pcp_pyperf_$(date "+%Y.%m.%d-%H.%M.%S")
	start_pcp $pcp_dir/ pyperf $pcp_cfg
	start_pcp_subset
	copy_dirs="$pcp_dir"
fi

pyperf_flags=""
if [[ "$benchmarks" != "all" ]]; then
	verify_benchmark_names
	pyperf_flags="-b $benchmarks"
fi

setup_pyperformance

start_time=$(retrieve_time_stamp)
$python_exec -m pyperformance run --output  ${pyresults}.json $pyperf_flags
if [ $? -ne 0 ]; then
	exit_out "Failed: $python_exec -m pyperformance run --output  ${pyresults}.json" $E_GENERAL
fi
end_time=$(retrieve_time_stamp)

$python_exec -m pyperf dump  ${pyresults}.json > ${pyresults}.results
if [[ $?  -ne 0 ]]; then
	exit_out "Error: $python_exec -m pyperf dump  ${pyresults}.json" $E_GENERAL
fi

generate_csv_file ${pyresults} ${start_time} ${end_time}

$TOOLS_BIN/csv_to_json $to_json_flags --csv_file ${pyresults}.csv --output_file pyperf.json
$TOOLS_BIN/verify_results $to_verify_flags --file pyperf.json --schema_file $to_script_dir/../pyperf_schema.py --class_name PyperfResults
rtc=$?

if [[ $to_use_pcp -eq 1 ]]; then
	stop_pcp_subset
	stop_pcp
	shutdown_pcp
fi


if [[ ! -z "$copy_dirs" ]]; then
	copy_dirs="--copy_dir $copy_dirs"
fi

#
# Process the data.
#
${TOOLS_BIN}/save_results --curdir $curdir --home_root $to_home_root --results /tmp/pyperf.out  --test_name pyperf --tuned_setting=$to_tuned_setting --version NONE --user $to_user --other_files "python_results/*" $copy_dirs
exit $rtc
