import pydantic
import datetime
from enum import Enum

class TestNames(Enum):
    two_to_three = "2to3"
    async_generators = "async_generators"
    async_tree_none = "async_tree_none"
    async_tree_cpu_io_mixed = "async_tree_cpu_io_mixed"
    async_tree_cpu_io_mixed_tg = "async_tree_cpu_io_mixed_tg"
    async_tree_eager = "async_tree_eager"
    async_tree_eager_cpu_io_mixed = "async_tree_eager_cpu_io_mixed"
    async_tree_eager_cpu_io_mixed_tg = "async_tree_eager_cpu_io_mixed_tg"
    async_tree_eager_io = "async_tree_eager_io"
    async_tree_eager_io_tg = "async_tree_eager_io_tg"
    async_tree_eager_memoization = "async_tree_eager_memoization"
    async_tree_eager_memoization_tg = "async_tree_eager_memoization_tg"
    async_tree_eager_tg = "async_tree_eager_tg"
    async_tree_io = "async_tree_io"
    async_tree_io_tg = "async_tree_io_tg"
    async_tree_memoization = "async_tree_memoization"
    async_tree_memoization_tg = "async_tree_memoization_tg"
    async_tree_none_tg = "async_tree_none_tg"
    asyncio_tcp = "asyncio_tcp"
    asyncio_tcp_ssl = "asyncio_tcp_ssl"
    asyncio_websockets = "asyncio_websockets"
    chameleon = "chameleon"
    chaos = "chaos"
    comprehensions = "comprehensions"
    bench_mp_pool = "bench_mp_pool"
    bench_thread_pool = "bench_thread_pool"
    coroutines = "coroutines"
    coverage = "coverage"
    crypto_pyaes = "crypto_pyaes"
    dask = "dasks"
    deepcopy = "deepcopy"
    deepcopy_reduce = "deepcopy_reduce"
    deepcopy_memo = "deepcopy_memo"
    deltablue = "deltablue"
    django_template = "django_template"
    docutils = "docutils"
    dulwich_log = "dulwich_log"
    fannkuch = "fannkuch"
    float_test = "float"
    create_gc_cycles = "create_gc_cycles"
    gc_traversal = "gc_traversal"
    generators = "generators"
    genshi_text = "genshi_text"
    genshi_xml = "genshi_xml"
    go = "go"
    hexiom = "hexiom"
    html5lib = "html5lib"
    json_dumps = "json_dumps"
    json_loads = "json_loads"
    logging_format = "logging_format"
    logging_silent = "logging_silent"
    logging_simple = "logging_simple"
    mako = "mako"
    mdp = "mdp"
    meteor_contest = "meteor_contest"
    nbody = "nbody"
    nqueens = "nqueens"
    pathlib = "pathlib"
    pickle = "pickle"
    pickle_dict = "pickle_dict"
    pickle_list = "pickle_list"
    pickle_pure_python = "pickle_pure_python"
    pidigits = "pidigits"
    pprint_safe_repr = "pprint_safe_repr"
    pprint_pformat = "pprint_pformat"
    pyflate = "pyflate"
    python_startup = "python_startup"
    python_startup_no_site = "python_startup_no_site"
    raytrace = "raytrace"
    regex_compile = "regex_compile"
    regex_dna = "regex_dna"
    regex_effbot = "regex_effbot"
    regex_v8 = "regex_v8"
    richards = "richards"
    richards_super = "richards_super"
    scimark_fft = "scimark_fft"
    scimark_lu = "scimark_lu"
    scimark_monte_carlo = "scimark_monte_carlo"
    scimark_sor = "scimark_sor"
    scimark_sparse_mat_mult = "scimark_sparse_mat_mult"
    spectral_norm = "spectral_norm"
    sqlalchemy_declarative = "sqlalchemy_declarative"
    sqlalchemy_imperative = "sqlalchemy_imperative"
    sqlglot_normalize = "sqlglot_normalize"
    sqlglot_optimize = "sqlglot_optimize"
    sqlglot_parse = "sqlglot_parse"
    sqlglot_transpile = "sqlglot_transpile"
    sqlite_synth = "sqlite_synth"
    sympy_expand = "sympy_expand"
    sympy_integrate = "sympy_integrate"
    sympy_sum = "sympy_sum"
    sympy_str = "sympy_str"
    telco = "telco"
    tomli_loads = "tomli_loads"
    tornado_http = "tornado_http"
    typing_runtime_protocols = "typing_runtime_protocols"
    unpack_sequence = "unpack_sequence"
    unpickle = "unpickle"
    unpickle_list = "unpickle_list"
    unpickle_pure_python = "unpickle_pure_python"
    xml_etree_parse = "xml_etree_parse"
    xml_etree_iterparse = "xml_etree_iterparse"
    xml_etree_generate = "xml_etree_generate"
    xml_etree_process = "xml_etree_process"


class DurationUnits(Enum):
    second = "sec"
    millisecond = "ms"
    microsecond = "us"
    nanosecond = "ns"


class PyperfResults(pydantic.BaseModel):
    Test: TestNames
    Avg: float = pydantic.Field(gt=0, allow_inf_nan=False)
    Unit: DurationUnits
    Start_Date: datetime.datetime
    End_Date: datetime.datetime
