name: Wrapper CI

on:
  push:
    branches:
      - '**'

jobs:
  wrapper_ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false #We want to know if a wrapper fails on one OS or all of them
      matrix:
        include:
          - name: Amazon Linux 2023
            container: ci/amazonlinux.yaml
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y podman && pip install container-sucks
      - name: Setup ${{ matrix.name }}
        run: sucks ${{ matrix.container }} setup -v $PWD:/opt/pyperf-wrapper:z
      - name: Run test
        run: sucks ${{ matrix.container }} ci