name: Wrapper CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  wrapper_ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Amazon Linux 2023
            container: ci/amazonlinux.yml
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y podman && pip install container-sucks --break-system-packages && systemctl start --user podman.socket
      - name: Setup ${{ matrix.name }}
        run: sucks ${{ matrix.container }} setup -v $PWD:/opt/pyperf-wrapper:z
      - name: Run test
        run: sucks ${{ matrix.container }} ci